#!/usr/bin/env bash
# Render ansible/inventory/hosts.yml from live Terraform state.
# Public IPs rotate on stop/start, so refresh state first, then read the hosts output.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INFRA="$ROOT/infra"
OUT="$ROOT/ansible/inventory/hosts.yml"
mkdir -p "$(dirname "$OUT")"

echo "refreshing terraform state (public IPs rotate on start/stop)..."
terraform -chdir="$INFRA" apply -refresh-only -auto-approve >/dev/null

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
terraform -chdir="$INFRA" output -json hosts >"$TMP"

# Python reads the JSON from a file arg (not stdin) so the heredoc program and the
# terraform output don't fight over stdin.
python3 - "$TMP" "$OUT" <<'PY'
import json, sys

hosts = json.load(open(sys.argv[1]))
out_path = sys.argv[2]

group_of = {"app": "app", "db": "db", "monitoring": "monitoring", "control": "control"}
groups = {}
for name, h in hosts.items():
    groups.setdefault(group_of.get(h["role"], h["role"]), {})[name] = h

lines = ["# GENERATED by scripts/gen-inventory.sh — do not edit.", "all:", "  children:"]
for g in sorted(groups):
    lines += [f"    {g}:", "      hosts:"]
    for name in sorted(groups[g]):
        h = groups[g][name]
        lines += [
            f"        {name}:",
            f"          ansible_host: {h['public_ip']}",
            f"          private_ip: {h['private_ip']}",
        ]

open(out_path, "w").write("\n".join(lines) + "\n")
print(f"wrote {out_path} ({len(hosts)} hosts)")
PY
